fn good() {
    a = 5
    medium()
}

fn medium() {
    a = nil
    bad()
}

fn bad() {
    a = nil + nil
}

pub fn test() {
    res = false
    try {
        good()
        print("[Error] good() should've thrown an exception by now!\n")
    } catch(RuntimeException e) {
        res = true
    }

    ret res
}
